### PR TITLE
Update list of deno subcommands

### PR DESCRIPTION
**Pull request by jsejcksn**
Ref: https://github.com/hayd/deno-docker/issues/119

### CODE REVIEW

**Comment by jsejcksn** [comment]
@hayd You [mentioned](https://github.com/hayd/deno-docker/issues/119#issuecomment-814730248) potentially using some of the code from the script I posted in [this comment](https://github.com/hayd/deno-docker/issues/119#issue-851876807) as a test, but I'm not sure how you were thinking about its implementation. If you have specifics to share, I'd be happy to make an effort at updating this PR with an implementation.

**Comment by hayd** [comment]
Happy to merge this first, since it's clearly a useful fix!

RE a test I was imagining (though other approaches would be fine!):
- get array of deno subcommands (by parsing deno --help ?)
- get array of subcommands listed in _entry.sh (look up the line?)
- check the arrays are equal :)

Another way, might be to have a script that updates the _entry.sh subcommands, run it in the tests and assert there's no git diff...

**Comment by hayd** [comment]
thanks!

**Comment by jsejcksn** [comment]
> * get array of subcommands listed in _entry.sh (look up the line?)

This seems ok to me, but it:
  - would require knowing how to target the line (with a regular expression, for example)
  - might be a brittle approach, because if the file changes, the regex could potentially become invalid and fail to match

> Another way, might be to have a script that updates the _entry.sh subcommands, run it in the tests and assert there's no git diff...

I like this approach because it can allow for using the same script to both generate the file and verify it between Deno version updates.

Yet another way could be to get the list of subcommands directly from the Deno repo. I did a search for this before writing the parsing script, but could not find it in the source. Do you have any ideas where the list might be?

**Comment by hayd** [comment]
something like:

```
const p =  Deno.run({"cmd": ["deno", "--help"], stdout: "piped",})

const out = new TextDecoder().decode(await p.output())
out.match(/\nSUBCOMMANDS:\n(.*)\n\n/s)[1].split("\n").map((line) => line.split(/\s+/)[1])
```
If this changes in future then it would fail the test :) so not so worried about brittleness.

I don't think there is a way to get it from js (since it's generated by clap).

**Comment by jsejcksn** [comment]
> If this changes in future then it would fail the test :) so not so worried about brittleness.

I'm not sure I follow you. Perhaps there has been some miscommunication... in my previous message I was referring to [`_enrtry.sh`](https://github.com/hayd/deno-docker/blob/master/_entry.sh):

> > * get array of subcommands listed in _entry.sh (look up the line?)
> 
> ...
>
> * might be a brittle approach, because if the file changes, the regex could potentially become invalid and fail to match

but it seems like you were describing an alternative to the method I was using in the script I posted in [this comment](https://github.com/hayd/deno-docker/issues/119#issue-851876807). I'll just create a PR from the work I did yesterday and we can discuss there how and what to change in order to arrive at the best solution.

**Pull request merged**
