### PR TITLE
change to a standard, explicit user creation

### PR DESCRIPTION
**Pull request by kinghat**
used the long commands for readability. fixes: https://github.com/hayd/deno-docker/issues/126. im not sure if there are other edge cases where a non standard uid/gid would get in the way but it makes it better for vscode tooling.

if you dont mind being this explicit ill leave it as is, otherwise if we assume the `addgroup` and `adduser` defaults we can go this route but who knows if the defaults will ever change on alpines end:
```
addgroup deno
adduser --disabled-password deno --ingroup deno
```

### CODE REVIEW

**Comment by hayd** [comment]
What is the benefit of being explicit? (I am okay with it, since this is what node dockerfile does but it would be nice to know why)

**Comment by kinghat** [comment]
> What is the benefit of being explicit? (I am okay with it, since this is what node dockerfile does but it would be nice to know why)

explicit for a couple reasons. the defaults changing from under us, which shouldnt happen, and i guess documentation in syntax :man_shrugging: those seem like pretty flimsy arguments, though. i mean should we then be explicit with all of the `adduser` defaults? here are those from the alpine/busybox documentation:
https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user#Creating_a_new_user

> - prompt to set a password for the new user.
> - create a home directory in /home/<username>
> - set the shell to the one used by the root account (ash by default)
> - assign user ID and group ID at 1000+
> - set the GECOS (full name) field to "Linux User,,,".

so doing:
```
addgroup deno
adduser --disabled-password deno --ingroup deno
```
is assuming all defaults but the long form flags for readability. we are inheriting the default shell from root as `/bin/ash` but we could change it to `/bin/sh` too :thinking: 

whatever you want to do is fine im only adamant about long form flags. if we should be explicit on the defaults, should we be explicit on all defaults?

**Comment by hayd** [comment]
I kinda want it to still be 1993. 😆 

But overall this is reasonable. Let's discuss ash vs sh in another issue/PR.

**Comment by kinghat** [comment]
> I kinda want it to still be 1993. laughing
ya i get it, but its not really user facing so nobody sees it anyways, like the exposed port.

> But overall this is reasonable. Let's discuss ash vs sh in another issue/PR.

ok so just leave the group and user changes the way they are?

**Comment by hayd** [comment]
Thanks! Included in 1.10.1.

**Pull request merged**
