### PR TITLE
Bump to 1.1.0

### PR DESCRIPTION
**Pull request by bios21**
Update to deno 1.1.0 and std 0.57.0

### CODE REVIEW

**Comment by hayd** [comment]
Great! Thank you!

Hopefully this will work on lambda 🤞

**Comment by bios21** [comment]
I'm currently trying with it.

**Comment by hayd** [comment]
Note: It'll take a 15min to publish (I don't think I have github actions caching working).

https://github.com/hayd/deno-docker/runs/766362560?check_suite_focus=true

**Comment by bios21** [comment]
Yeah I know, that's why I started the build locally while waiting for the PR to be merged.

**Pull request merged**
